rgname                 = "dev-piyush-rg"
service_principal_name = "dev-piyush-spn"
keyvault_name          = "dev-piyush-kv-101"
SUB_ID = "f30f4f95-ede5-4f68-aa0c-811033ee0007"
#cluster_name = "dev-piyush-cluster"
#node_pool_name = "devnp"